# Generated by Django 4.0.6 on 2023-05-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='data_encerramento',
            field=models.DateField(null=True, verbose_name='Data de encerramento'),
        ),
    ]
